# Regression - Video Game Total Earnings Prediction

In [1]:
import keras

Using TensorFlow backend.


In [0]:
import pandas as pd

## Load training data set from CSV file
training_data_df = pd.read_csv("/content/sample_data/sales_data_training.csv")

## Load testing data set from CSV file
test_data_df = pd.read_csv("/content/sample_data/sales_data_test.csv")

In [3]:
training_data_df.describe()

critic_rating    is_action  is_exclusive_to_us  is_portable  \
count    1000.000000  1000.000000         1000.000000   1000.00000   
mean        3.660000     0.466000            0.267000      0.24300   
std         0.834024     0.499092            0.442614      0.42911   
min         2.000000     0.000000            0.000000      0.00000   
25%         3.000000     0.000000            0.000000      0.00000   
50%         3.750000     0.000000            0.000000      0.00000   
75%         4.500000     1.000000            1.000000      0.00000   
max         5.000000     1.000000            1.000000      1.00000   

       is_role_playing    is_sequel    is_sports  suitable_for_kids  \
count      1000.000000  1000.000000  1000.000000        1000.000000   
mean          0.347000     0.746000     0.187000           0.270000   
std           0.476254     0.435515     0.390107           0.444182   
min           0.000000     0.000000     0.000000           0.000000   
25%           0.000000     0.000000     0.000000           0.000000   
50%           0.000000     1.000000     0.000000           0.000000   
75%           1.000000     1.000000     0.000000           1.000000   
max           1.000000     1.000000     1.000000           1.000000   

        unit_price  total_earnings  
count  1000.000000     1000.000000  
mean     54.170000   110705.229000  
std       8.036927    44970.558163  
min      39.990000    31355.000000  
25%      49.990000    78830.250000  
50%      59.990000   104335.500000  
75%      59.990000   133271.000000  
max      59.990000   301860.000000

In [0]:
training_data_df.head()

critic_rating  is_action  is_exclusive_to_us  is_portable  is_role_playing  \
0            3.5          1                   0            1                0   
1            4.5          0                   0            0                0   
2            3.0          0                   0            0                0   
3            4.5          1                   0            0                0   
4            4.0          1                   0            1                0   

   is_sequel  is_sports  suitable_for_kids  unit_price  total_earnings  
0          1          0                  0       59.99          132717  
1          1          1                  0       49.99           83407  
2          1          1                  0       49.99           62423  
3          0          0                  1       39.99           69889  
4          1          0                  1       59.99          161382

## Data Pre-Processing

In [0]:
from sklearn.preprocessing import MinMaxScaler

## Data needs to be scaled to a small range like 0 to 1 for the neural
## network to work well.
scaler = MinMaxScaler(feature_range=(0, 1))

## Scale both the training inputs and outputs
scaled_training = scaler.fit_transform(training_data_df)
scaled_testing = scaler.transform(test_data_df)

## Create new pandas DataFrame objects from the scaled data
scaled_training_df = pd.DataFrame(scaled_training, columns=training_data_df.columns.values)
scaled_testing_df = pd.DataFrame(scaled_testing, columns=test_data_df.columns.values)

## Save scaled data dataframes to new CSV files
scaled_training_df.to_csv("sales_data_training_scaled.csv", index=False)
scaled_testing_df.to_csv("sales_data_testing_scaled.csv", index=False)

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


## Network Modelling

In [0]:
import pandas as pd
from keras.models import Sequential
from keras.layers import *

training_data_df = pd.read_csv("sales_data_training_scaled.csv")

X = training_data_df.drop('total_earnings', axis=1).values
Y = training_data_df[['total_earnings']].values

len(X[0])

9

In [0]:
## Define the model
model = Sequential()
model.add(Dense(50, input_dim=9, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(50, activation='relu'))
model.add(Dense(1, activation='linear'))
model.compile(loss='mean_squared_error', optimizer='adam')

model.summary()

Instructions for updating:
Colocations handled automatically by placer.
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 50)                500       
_________________________________________________________________
dense_2 (Dense)              (None, 100)               5100      
_________________________________________________________________
dense_3 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 51        
Total params: 10,701
Trainable params: 10,701
Non-trainable params: 0
_________________________________________________________________


In [0]:
## Train the model
model.fit(
    X,
    Y,
    epochs=50,
    shuffle=True,
    verbose=2
)

Instructions for updating:
Use tf.cast instead.
Epoch 1/50
 - 0s - loss: 0.0260
Epoch 2/50
 - 0s - loss: 0.0036
Epoch 3/50
 - 0s - loss: 9.3819e-04
Epoch 4/50
 - 0s - loss: 4.4225e-04
Epoch 5/50
 - 0s - loss: 3.0187e-04
Epoch 6/50
 - 0s - loss: 2.2030e-04
Epoch 7/50
 - 0s - loss: 1.6874e-04
Epoch 8/50
 - 0s - loss: 1.4373e-04
Epoch 9/50
 - 0s - loss: 1.0225e-04
Epoch 10/50
 - 0s - loss: 8.7689e-05
Epoch 11/50
 - 0s - loss: 8.4728e-05
Epoch 12/50
 - 0s - loss: 7.7403e-05
Epoch 13/50
 - 0s - loss: 6.7571e-05
Epoch 14/50
 - 0s - loss: 5.6388e-05
Epoch 15/50
 - 0s - loss: 6.2357e-05
Epoch 16/50
 - 0s - loss: 5.3183e-05
Epoch 17/50
 - 0s - loss: 4.4902e-05
Epoch 18/50
 - 0s - loss: 4.0879e-05
Epoch 19/50
 - 0s - loss: 3.9540e-05
Epoch 20/50
 - 0s - loss: 4.1696e-05
Epoch 21/50
 - 0s - loss: 3.9129e-05
Epoch 22/50
 - 0s - loss: 3.4138e-05
Epoch 23/50
 - 0s - loss: 3.2561e-05
Epoch 24/50
 - 0s - loss: 3.0748e-05
Epoch 25/50
 - 0s - loss: 3.0542e-05
Epoch 26/50
 - 0s - loss: 2.6957e-05
Epoch 2

In [0]:
## Load the separate test data set
test_data_df = pd.read_csv("sales_data_testing_scaled.csv")

X_test = test_data_df.drop('total_earnings', axis=1).values
Y_test = test_data_df[['total_earnings']].values

test_error_rate = model.evaluate(X_test, Y_test, verbose=0)
print("Mean squared error (MSE) : {}".format(test_error_rate))

Mean squared error (MSE) : 0.00011294027237454429


In [0]:
## Load the data we make to use to make a prediction
X = pd.read_csv("sample_data/proposed_new_product.csv").values

## Make a prediction with the neural network
prediction = model.predict(X)

prediction

array([[0.85710084]], dtype=float32)

In [0]:
scaler.inverse_transform(np.hstack((X,prediction)))

array([[4.10000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
        5.59900000e+01, 2.63205064e+05]])

In [0]:
## Save the model to disk in hdf5 - Convention
model.save("trained_model.h5")
print("Model saved to disk.")

Model saved to disk.


In [0]:
%precision 2

import pandas as pd
from keras.models import load_model

model = load_model('trained_model.h5')

X = pd.read_csv("sample_data/multiple_products.csv")
X['total_earnings']=0
X

critic_rating  is_action  is_exclusive_to_us  is_portable  is_role_playing  \
0            4.2          1                   1            1                0   
1            3.9          1                   0            1                0   
2            3.3          1                   1            1                1   
3            2.8          1                   1            0                1   

   is_sequel  is_sports  suitable_for_kids  unit_price  total_earnings  
0          1          0                  1          55               0  
1          0          1                  1          37               0  
2          1          0                  1          87               0  
3          1          1                  0          92               0

In [0]:
X_scaled=scaler.transform(X)
X_df=pd.DataFrame(X_scaled, columns=X.columns.values)

X_train=X_df.drop(['total_earnings'],axis=1).values

prediction = model.predict(X_train)

result=scaler.inverse_transform(np.hstack((X_train,prediction)))
result[:,-1]

array([263254.97,  43674.86, 218575.86, 160256.15])