# Classification

In [0]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [2]:
datafile = "/content/sample_data/titanic.csv"
data = pd.read_csv(datafile)

data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
data['Gender']=data['Sex'].apply(lambda a: 1 if a=='male' else 0)

data=data.drop(['PassengerId','Name','Cabin','Embarked','Ticket','Sex'],axis=1)

data=data.dropna()

data.head()

Survived  Pclass   Age  SibSp  Parch     Fare  Gender
0         0       3  22.0      1      0   7.2500       1
1         1       1  38.0      1      0  71.2833       0
2         1       3  26.0      0      0   7.9250       0
3         1       1  35.0      1      0  53.1000       0
4         0       3  35.0      0      0   8.0500       1

In [4]:
# Normalize Data
scaler = MinMaxScaler(feature_range=(0, 1))

scaled_data = scaler.fit_transform(data)

scaled_df = pd.DataFrame(scaled_data, columns=data.columns.values)

# Create the X and y arrays
X = scaled_df.drop(['Survived'],axis=1).as_matrix()
y = scaled_df['Survived'].as_matrix()

# Split the data set in a training set (70%) and a test set (30%)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

X_train, X_test, y_train, y_test 

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


(array([[1.        , 0.32143755, 0.4       , 0.        , 0.01690807,
         1.        ],
        [0.5       , 0.3842674 , 0.2       , 0.16666667, 0.05123659,
         0.        ],
        [0.        , 0.43453129, 0.        , 0.        , 1.        ,
         0.        ],
        ...,
        [0.5       , 0.03242021, 0.2       , 0.16666667, 0.03659756,
         1.        ],
        [1.        , 0.22090978, 0.        , 0.16666667, 0.01824998,
         0.        ],
        [0.5       , 0.54762503, 0.2       , 0.        , 0.05074862,
         1.        ]]),
 array([[1.        , 0.19577783, 0.        , 0.        , 0.01512699,
         0.        ],
        [0.        , 0.67328474, 0.        , 0.16666667, 0.15085515,
         1.        ],
        [0.5       , 0.23347575, 0.        , 0.        , 0.02049464,
         1.        ],
        ...,
        [0.5       , 0.48479517, 0.        , 0.        , 0.02537431,
         1.        ],
        [1.        , 0.48479517, 0.        , 0.        , 0.015

In [5]:
print(data.columns)
print(len(data.columns))

Index(['Survived', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare', 'Gender'], dtype='object')
7


In [6]:
import keras
from keras.layers import *
from keras.models import Sequential

Using TensorFlow backend.


In [7]:
model=Sequential()
model.add(Dense(10,input_dim=6,activation='relu'))
model.add(Dense(100))
model.add(Dense(1))

Instructions for updating:
Colocations handled automatically by placer.


In [8]:
# Binary Classification Loss
model.compile(loss="binary_crossentropy",optimizer='adam')

# Batch Size: Size of data to be passed for each epoch
# Validation Data: Test Data for Analysis
model.fit(X_train,y_train,shuffle=True, batch_size=32, validation_data=(X_test,y_test),epochs=10)

Instructions for updating:
Use tf.cast instead.
Train on 499 samples, validate on 215 samples
Epoch 1/10
499/499 [==============================] - 0s 766us/step - loss: 0.9977 - val_loss: 0.8029
Epoch 2/10
499/499 [==============================] - 0s 66us/step - loss: 0.7701 - val_loss: 0.6886
Epoch 3/10
499/499 [==============================] - 0s 68us/step - loss: 0.6752 - val_loss: 0.6348
Epoch 4/10
499/499 [==============================] - 0s 64us/step - loss: 0.6232 - val_loss: 0.5881
Epoch 5/10
499/499 [==============================] - 0s 70us/step - loss: 0.5807 - val_loss: 0.5558
Epoch 6/10
499/499 [==============================] - 0s 93us/step - loss: 0.5457 - val_loss: 0.5275
Epoch 7/10
499/499 [==============================] - 0s 78us/step - loss: 0.5147 - val_loss: 0.5081
Epoch 8/10
499/499 [==============================] - 0s 56us/step - loss: 0.4934 - val_loss: 0.4988
Epoch 9/10
499/499 [==============================] - 0s 59us/step - loss: 0.4838 - val_loss: 0.4

In [9]:
model.evaluate(X_test,y_test)

215/215 [==============================] - 0s 46us/step


0.5418991415999657

In [10]:
model.predict(X_test)

array([[5.43343604e-01],
       [3.21020961e-01],
       [2.85372972e-01],
       [1.49411485e-01],
       [2.21791431e-01],
       [6.11946583e-01],
       [3.66323560e-01],
       [1.61119506e-01],
       [1.86773613e-01],
       [2.34117925e-01],
       [1.93733737e-01],
       [1.15182325e-01],
       [2.00802803e-01],
       [3.88075709e-01],
       [5.57112098e-01],
       [1.37863100e-01],
       [3.24225456e-01],
       [1.79171219e-01],
       [8.55802655e-01],
       [8.49364400e-01],
       [1.96400762e-01],
       [1.22510582e-01],
       [6.73140228e-01],
       [8.39306414e-01],
       [2.37171009e-01],
       [3.10615003e-01],
       [1.94809586e-01],
       [2.36936510e-02],
       [9.70205963e-02],
       [3.45507413e-01],
       [1.90594614e-01],
       [4.57561642e-01],
       [3.67267400e-01],
       [1.98744774e-01],
       [4.54817653e-01],
       [1.23502940e-01],
       [1.84832051e-01],
       [1.93776861e-01],
       [1.79852337e-01],
       [2.64473055e-02],


In [11]:
prediction=model.predict_classes(X_test).flatten()

pd.DataFrame({"Pred":prediction, "Actual":y_test},columns=['Pred',"Actual"])

Pred  Actual
0       1     1.0
1       0     0.0
2       0     0.0
3       0     0.0
4       0     0.0
5       1     1.0
6       0     1.0
7       0     0.0
8       0     0.0
9       0     0.0
10      0     0.0
11      0     1.0
12      0     1.0
13      0     0.0
14      1     1.0
15      0     1.0
16      0     0.0
17      0     0.0
18      1     1.0
19      1     1.0
20      0     0.0
21      0     0.0
22      1     1.0
23      1     1.0
24      0     0.0
25      0     0.0
26      0     1.0
27      0     0.0
28      0     0.0
29      0     1.0
..    ...     ...
185     0     0.0
186     0     0.0
187     0     0.0
188     0     0.0
189     0     0.0
190     0     0.0
191     1     1.0
192     0     1.0
193     1     1.0
194     1     1.0
195     1     1.0
196     0     0.0
197     1     1.0
198     0     0.0
199     0     0.0
200     1     1.0
201     1     1.0
202     0     0.0
203     0     1.0
204     1     0.0
205     1     1.0
206     0     1.0
207     1     1.0
208     0     0.0
209     1     0.0
210     0     0.0
211     0     1.0
212     0     0.0
213     0     0.0
214     0     0.0

[215 rows x 2 columns]

## Additional Performance Metrics

In [0]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,prediction)

array([[106,  24],
       [ 29,  56]])

In [0]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,prediction)

0.7534883720930232